title: cd-intermediate-python-sushi
hero_image: images/banner.png
description: cd-intermediate-python-sushi description
version: 4
listed: false
copyedit: false
last_tested: "2018-06-06"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
